name: Discord Bot Status Check

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y jq curl

      - name: Set Environment Variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "NETLIFY_TOKEN=${{ secrets.NETLIFY_TOKEN }}" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> $GITHUB_ENV



      - name: Fetch Deployment Data
        run: |
          curl --silent --fail -H "Authorization: Bearer $VERCEL_TOKEN" \
               -X GET "https://api.vercel.com/v6/deployments" > vercel.json || echo "[]" > vercel.json
          curl --silent --fail -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
               -H "Content-Type: application/json" \
               -X GET "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/" > cloudflare.json || echo "{\"result\":[]}" > cloudflare.json
          curl --silent --fail -H "Authorization: Bearer $NETLIFY_TOKEN" \
               -X GET "https://api.netlify.com/api/v1/sites" > netlify.json || echo "[]" > netlify.json
  
      - name: Format Status Report
        run: python format.py
  
      - name: Send Message to Discord
        run: python send_discord_message.py
  