name: Discord Bot Status Check

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch: # Allows manual execution
  push:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git pull origin $(git rev-parse --abbrev-ref HEAD)

      - name: Install Dependencies
        run: sudo apt-get install -y jq

      - name: Set Environment Variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "NETLIFY_TOKEN=${{ secrets.NETLIFY_TOKEN }}" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> $GITHUB_ENV

      - name: Get Vercel Deployments for All Projects
        run: |
          curl --silent --fail -H "Authorization: Bearer $VERCEL_TOKEN" \
               -X GET "https://api.vercel.com/v6/deployments" > vercel.json || echo "[]" > vercel.json

      - name: Get Cloudflare Pages Projects
        run: |
          curl --silent --fail -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
               -H "Content-Type: application/json" \
               -X GET "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/" > cloudflare.json || echo "{\"result\":[]}" > cloudflare.json

      - name: Get Netlify Sites Info
        run: |
          curl --silent --fail -H "Authorization: Bearer $NETLIFY_TOKEN" \
               -X GET "https://api.netlify.com/api/v1/sites" > netlify.json || echo "[]" > netlify.json

      - name: Format Status Message
        run: |
          echo "**Project Status Update:**" > status.txt
          
          echo "- **Vercel Deployments:**" >> status.txt
          if [[ $(jq '.deployments | length' vercel.json) -gt 0 ]]; then
            jq -r '.deployments[] | "  - **Project:** " + (.name // "Unknown") + 
                   "\n    **Status:** " + (.state // "Unknown") + 
                   "\n    **Latest Deploy URL:** " + (.url // "No URL")' vercel.json >> status.txt
          else
            echo "  - No deployments found" >> status.txt
          fi
          
          echo "- **Cloudflare Pages Projects:**" >> status.txt
          if [[ $(jq '.result | length' cloudflare.json) -gt 0 ]]; then
            jq -r '.result[] | "  - **Project:** " + (.name // "Unknown") + 
                   "\n    **Status:** " + (.status // "Unknown") + 
                   "\n    **Last Deployed:** " + (.latest_deployment.created_on | tostring // "Unknown")' cloudflare.json >> status.txt
          else
            echo "  - No projects found" >> status.txt
          fi
          
          echo "- **Netlify Sites:**" >> status.txt
          if [[ $(jq '. | length' netlify.json) -gt 0 ]]; then
            jq -r '.[] | "  - **Site:** " + (.name // "Unknown") + 
                   "\n    **State:** " + (.state // "Unknown") + 
                   "\n    **Latest Deploy URL:** " + (.url // "No URL") + 
                   "\n    **Last Published:** " + (.published_at | tostring // "Unknown")' netlify.json >> status.txt
          else
            echo "  - No sites found" >> status.txt
          fi

      - name: Send Message to Discord using Python
        run: python send_discord_message.py